_REGION = {
    'Angeles Forest': (
        'Los Angeles - Angeles National Forest',
        'Unincorporated - Angeles National Forest',
        'Unincorporated - Kagel/Lopez Canyons',
        'Unincorporated - Placerita Canyon',
        'Unincorporated - Sand Canyon'
    ),
    'Antelope Valley': (
        'City of Lancaster',
        'City of Palmdale',
        'Unincorporated - Acton',
        'Unincorporated - Anaverde',
        'Unincorporated - Del Sur',
        'Unincorporated - Desert View Highlands',
        'Unincorporated - East Lancaster',
        'Unincorporated - Elizabeth Lake',
        'Unincorporated - Hi Vista',
        'Unincorporated - Lake Los Angeles',
        'Unincorporated - Leona Valley',
        'Unincorporated - Littlerock',
        'Unincorporated - Littlerock/Juniper Hills',
        'Unincorporated - Littlerock/Pearblossom',
        'Unincorporated - Llano',
        'Unincorporated - North Lancaster',
        'Unincorporated - Palmdale',
        'Unincorporated - Pearblossom/Llano',
        'Unincorporated - Quartz Hill',
        'Unincorporated - Roosevelt',
        'Unincorporated - South Antelope Valley',
        'Unincorporated - South Edwards',
        'Unincorporated - Southeast Antelope Valley',
        'Unincorporated - Sun Village',
        'Unincorporated - West Antelope Valley',
        'Unincorporated - White Fence Farms'
    ),
    'Central LA': (
        'City of West Hollywood',
        'Los Angeles - Angelino Heights',
        'Los Angeles - Brookside',
        'Los Angeles - Cadillac-Corning',
        'Los Angeles - Carthay',
        'Los Angeles - Chinatown',
        'Los Angeles - Cloverdale/Cochran',
        'Los Angeles - Country Club Park',
        'Los Angeles - Crestview',
        'Los Angeles - Downtown',
        'Los Angeles - East Hollywood',
        'Los Angeles - Echo Park',
        'Los Angeles - Elysian Park',
        'Los Angeles - Faircrest Heights',
        'Los Angeles - Hancock Park',
        'Los Angeles - Harvard Heights',
        'Los Angeles - Historic Filipinotown',
        'Los Angeles - Hollywood',
        'Los Angeles - Hollywood Hills',
        'Los Angeles - Koreatown',
        'Los Angeles - Lafayette Square',
        'Los Angeles - Little Armenia',
        'Los Angeles - Little Bangladesh',
        'Los Angeles - Little Tokyo',
        'Los Angeles - Longwood',
        'Los Angeles - Los Feliz',
        'Los Angeles - Melrose',
        'Los Angeles - Miracle Mile',
        'Los Angeles - Mid-city',
        'Los Angeles - Park La Brea',
        'Los Angeles - Pico-Union',
        'Los Angeles - Regent Square',
        'Los Angeles - Reynier Village',
        'Los Angeles - Silverlake',
        'Los Angeles - South Carthay',
        'Los Angeles - St Elmo Village',
        'Los Angeles - Sycamore Square',
        'Los Angeles - Temple-Beaudry',
        'Los Angeles - Thai Town',
        'Los Angeles - Westlake',
        'Los Angeles - Victoria Park',
        'Los Angeles - Wellington Square',
        'Los Angeles - Wholesale District',
        'Los Angeles - Wilshire Center',
        'Unincorporated - Franklin Canyon',
        'Unincorporated - Miracle Mile'
    ),
    'Eastside': (
        'Unincorporated - Bandini Islands',
        'Los Angeles - Boyle Heights',
        'Los Angeles - El Sereno',
        'Los Angeles - Lincoln Heights',
        'Los Angeles - University Hills',
        'Unincorporated - East Los Angeles'
    ),
    'Harbor': (
        'City of Avalon',
        'City of Carson',
        'City of Hawaiian Gardens',
        'City of Lakewood',
        'City of Long Beach',
        'City of Signal Hill',
        'Los Angeles - Harbor City',
        'Los Angeles - Harbor Gateway',
        'Los Angeles - Harbor Pines',
        'Los Angeles - San Pedro',
        'Los Angeles - Wilmington',
        'Unincorporated - Harbor Gateway',
        'Unincorporated - La Rambla',
        'Unincorporated - Lakewood',
        'Unincorporated - Long Beach',
        'Unincorporated - Rancho Dominguez',
        'Unincorporated - San Clemente Island',
        'Unincorporated - Santa Catalina Island',
        'Unincorporated - West Carson',
        'Unincorporated - West Rancho Dominguez'
    ),
    'Northeast LA': (
        'Los Angeles - Atwater Village',
        'Los Angeles - Eagle Rock',
        'Los Angeles - Elysian Valley',
        'Los Angeles - Glassell Park',
        'Los Angeles - Highland Park',
        'Los Angeles - Mt. Washington'
    ),
    'Northwest County': (
        'City of Santa Clarita',
        'Unincorporated - Agua Dulce',
        'Unincorporated - Bouquet Canyon',
        'Unincorporated - Canyon Country',
        'Unincorporated - Castaic',
        'Unincorporated - Lake Hughes',
        'Unincorporated - Newhall',
        'Unincorporated - San Francisquito Canyon/Bouquet Canyon',
        'Unincorporated - Saugus',
        'Unincorporated - Saugus/Canyon Country',
        'Unincorporated - Stevenson Ranch',
        'Unincorporated - Twin Lakes/Oat Mountain',
        'Unincorporated - Val Verde',
        'Unincorporated - Valencia'
    ),
    'Pomona Valley': (
        'City of Claremont',
        'City of La Verne',
        'City of Pomona',
        'Unincorporated - Claremont',
        'Unincorporated - La Verne',
        'Unincorporated - Padua Hills',
    ),
    'San Fernando Valley': (
        'City of Burbank',
        'City of San Fernando',
        'Los Angeles - Arleta',
        'Los Angeles - Canoga Park',
        'Los Angeles - Chatsworth',
        'Los Angeles - Encino',
        'Los Angeles - Granada Hills',
        'Los Angeles - Lake Balboa',
        'Los Angeles - Lakeview Terrace',
        'Los Angeles - Mission Hills',
        'Los Angeles - North Hills',
        'Los Angeles - North Hollywood',
        'Los Angeles - Northridge',
        'Los Angeles - Pacoima',
        'Los Angeles - Panorama City',
        'Los Angeles - Porter Ranch',
        'Los Angeles - Reseda',
        'Los Angeles - Reseda Ranch',
        'Los Angeles - Shadow Hills',
        'Los Angeles - Sherman Oaks',
        'Los Angeles - Studio City',
        'Los Angeles - Sun Valley',
        'Los Angeles - Sylmar',
        'Los Angeles - Tarzana',
        'Los Angeles - Toluca Lake',
        'Los Angeles - Toluca Terrace',
        'Los Angeles - Toluca Woods',
        'Los Angeles - Valley Glen',
        'Los Angeles - Valley Village',
        'Los Angeles - Van Nuys',
        'Los Angeles - West Hills',
        'Los Angeles - Winnetka',
        'Los Angeles - Woodland Hills',
        'Unincorporated - Lake Manor',
        'Unincorporated - Universal City',
        'Unincorporated - West Chatsworth',
        'Unincorporated - Westhills'
    ),
    'San Gabriel Valley': (
        'City of Alhambra',
        'City of Arcadia',
        'City of Azusa',
        'City of Baldwin Park',
        'City of Bradbury',
        'City of Covina',
        'City of Diamond Bar',
        'City of Duarte',
        'City of El Monte',
        'City of Glendora',
        'City of Industry',
        'City of Irwindale',
        'City of La Habra Heights',
        'City of La Puente',
        'City of Monrovia',
        'City of Monterey Park',
        'City of Rosemead',
        'City of San Dimas',
        'City of San Gabriel',
        'City of San Marino',
        'City of Sierra Madre',
        'City of South El Monte',
        'City of South Pasadena',
        'City of Temple City',
        'City of Walnut',
        'City of West Covina',
        'City of Whittier',
        'Unincorporated - Arcadia',
        'Unincorporated - Avocado Heights',
        'Unincorporated - Azusa',
        'Unincorporated - Bassett',
        'Unincorporated - Bradbury',
        'Unincorporated - Charter Oak',
        'Unincorporated - Covina',
        'Unincorporated - Covina (Charter Oak)',
        'Unincorporated - Duarte',
        'Unincorporated - East Covina',
        'Unincorporated - East Pasadena',
        'Unincorporated - El Monte',
        'Unincorporated - Glendora',
        'Unincorporated - Hacienda Heights',
        'Unincorporated - La Habra Heights',
        'Unincorporated - Monrovia',
        'Unincorporated - North Whittier',
        'Unincorporated - Northeast San Gabriel',
        'Unincorporated - Pellissier Village',
        'Unincorporated - Pomona',
        'Unincorporated - Rowland Heights',
        'Unincorporated - San Jose Hills',
        'Unincorporated - San Pasqual',
        'Unincorporated - South El Monte',
        'Unincorporated - South San Gabriel',
        'Unincorporated - Sunrise Village',
        'Unincorporated - Valinda',
        'Unincorporated - Walnut',
        'Unincorporated - West Puente Valley',
        'Unincorporated - Whittier',
        'Unincorporated - Whittier Narrows'
    ),
    'Santa Monica Mountains': (
        'City of Agoura Hills',
        'City of Calabasas',
        'City of Hidden Hills',
        'City of Malibu',
        'City of Westlake Village',
        'Unincorporated - Santa Monica Mountains'
    ),
    'South Bay': (
        'City of El Segundo',
        'City of Gardena',
        'City of Hawthorne',
        'City of Hermosa Beach',
        'City of Inglewood',
        'City of Lawndale',
        'City of Lomita',
        'City of Manhattan Beach',
        'City of Palos Verdes Estates',
        'City of Rancho Palos Verdes',
        'City of Redondo Beach',
        'City of Rolling Hills',
        'City of Rolling Hills Estates',
        'City of Torrance',
        'Los Angeles - Playa Del Rey',
        'Los Angeles - Westchester',
        'Unincorporated - Del Aire',
        'Unincorporated - El Camino Village',
        'Unincorporated - Hawthorne',
        'Unincorporated - Lennox',
        'Unincorporated - Palos Verdes Peninsula',
        'Unincorporated - Westfield/Academy Hills',
        'Unincorporated - Wiseburn'
    ),
    'South LA': (
        'Los Angeles - Adams-Normandie',
        'Los Angeles - Alsace',
        'Los Angeles - Baldwin Hills',
        'Los Angeles - Central',
        'Los Angeles - Century Palms/Cove',
        'Los Angeles - Crenshaw District',
        'Los Angeles - Exposition',
        'Los Angeles - Exposition Park',
        'Los Angeles - Figueroa Park Square',
        'Los Angeles - Florence-Firestone',
        'Los Angeles - Gramercy Place',
        'Los Angeles - Green Meadows',
        'Los Angeles - Harvard Park',
        'Los Angeles - Hyde Park',
        'Los Angeles - Jefferson Park',
        'Los Angeles - Leimert Park',
        'Los Angeles - Manchester Square',
        'Los Angeles - South Park',
        'Los Angeles - University Park',
        'Los Angeles - Vermont Knolls',
        'Los Angeles - Vermont Square',
        'Los Angeles - Vermont Vista',
        'Los Angeles - Vernon Central',
        'Los Angeles - View Heights',
        'Los Angeles - Watts',
        'Los Angeles - West Adams',
        'Los Angeles - West Vernon',
        'Unincorporated - Athens-Westmont',
        'Unincorporated - Athens Village',
        'Unincorporated - Florence-Firestone',
        'Unincorporated - View Park/Windsor Hills',
        'Unincorporated - Willowbrook'
    ),
    'Southeast': (
        'City of Artesia',
        'City of Bell',
        'City of Bell Gardens',
        'City of Bellflower',
        'City of Cerritos',
        'City of Commerce',
        'City of Compton',
        'City of Cudahy',
        'City of Downey',
        'City of Huntington Park',
        'City of La Mirada',
        'City of Lynwood',
        'City of Maywood',
        'City of Montebello',
        'City of Norwalk',
        'City of Paramount',
        'City of Pico Rivera',
        'City of Santa Fe Springs',
        'City of South Gate',
        'City of Vernon',
        'Unincorporated - Cerritos',
        'Unincorporated - East La Mirada',
        'Unincorporated - East Rancho Dominguez',
        'Unincorporated - East Whittier',
        'Unincorporated - Lynwood',
        'Unincorporated - Rosewood',
        'Unincorporated - Rosewood/East Gardena',
        'Unincorporated - Rosewood/West Rancho Dominguez',
        'Unincorporated - South Whittier',
        'Unincorporated - Walnut Park',
        'Unincorporated - West Whittier/Los Nietos'
    ),
    'Verdugos': (
        'City of Glendale',
        'City of La Canada Flintridge',
        'City of Sunland',
        'City of Pasadena',
        'Los Angeles - Sunland',
        'Los Angeles - Tujunga',
        'Unincorporated - Altadena',
        'Unincorporated - La Crescenta-Montrose'
    ),
    'Westside': (
        'City of Beverly Hills',
        'City of Culver City',
        'City of Santa Monica',
        'Los Angeles - Bel Air',
        'Los Angeles - Beverly Crest',
        'Los Angeles - Beverlywood',
        'Los Angeles - Brentwood',
        'Los Angeles - Century City',
        'Los Angeles - Cheviot Hills',
        'Los Angeles - Del Rey',
        'Los Angeles - Mandeville Canyon',
        'Los Angeles - Mar Vista',
        'Los Angeles - Marina Peninsula',
        'Los Angeles - Pacific Palisades',
        'Los Angeles - Palms',
        'Los Angeles - Playa Vista',
        'Los Angeles - Palisades Highlands',
        'Los Angeles - Rancho Park',
        'Los Angeles - Venice',
        'Los Angeles - West Los Angeles',
        'Los Angeles - Westwood',
        'Unincorporated - Del Rey',
        'Unincorporated - Ladera Heights',
        'Unincorporated - Marina del Rey',
        'Unincorporated - West LA'
    )
}

REGION_MAP = {}
for region in _REGION:
    for area in _REGION[region]:
        REGION_MAP[area] = region
REGION_MAP['Los Angeles'] = None
