from lac_covid19.const.lac_regions import HARBOR, SAN_GABRIEL_VALLEY

LONG_BEACH = 'Long Beach'
PASADENA = 'Pasadena'

_CSA_CITY = 'City of {}'
CSA_LB = _CSA_CITY.format(LONG_BEACH)
CSA_PAS = _CSA_CITY.format(PASADENA)

# US Census Table DP05 2018 5-year
POPULATION_LAC = 10_098_052
POPULATION_LONG_BEACH = 468_883
POPULATION_PASADENA = 141_246

HEALTH_DEPT_INFO = {
    LONG_BEACH: (CSA_LB, HARBOR, POPULATION_LONG_BEACH),
    PASADENA: (CSA_PAS, SAN_GABRIEL_VALLEY, POPULATION_PASADENA)
}
